#!/usr/bin/env bun
// Scripted setup only: no generated agent responses, review input or export implementation.
import { createHash } from "node:crypto";
import {
  cp,
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  stat,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";

const args = new Map(
  Bun.argv.slice(2).map((arg) => {
    const split = arg.indexOf("=");
    return [arg.slice(0, split), arg.slice(split + 1)];
  }),
);
for (const arg of Bun.argv.slice(2)) {
  if (!/^--(dest|cli-source)=.+/.test(arg))
    throw new Error(
      `Unknown argument: ${arg}; use --dest=/new/path or --cli-source=/path/to/packages/cli/src/index.ts`,
    );
}
const sourceRoot = resolve(import.meta.dir, "../..");
const fixture = join(sourceRoot, "examples/product-delivery");
const cliSource = resolve(
  args.get("--cli-source") ?? join(sourceRoot, "packages/cli/src/index.ts"),
);
if (!(await stat(cliSource)).isFile())
  throw new Error(`CLI source is not a file: ${cliSource}`);
const requestedDestination = args.get("--dest");
if (requestedDestination && !isAbsolute(requestedDestination))
  throw new Error("--dest must be an absolute, previously nonexistent path");
const destination = requestedDestination
  ? resolve(requestedDestination)
  : await mkdtemp(join(tmpdir(), "beacon-rehearsal-"));
if (requestedDestination) await mkdir(destination); // Existing destinations are deliberately refused.

const commands: { command: string[]; stdout: string }[] = [];
async function run(command: string[]) {
  const process = Bun.spawn(command, {
    cwd: destination,
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, code] = await Promise.all([
    new Response(process.stdout).text(),
    new Response(process.stderr).text(),
    process.exited,
  ]);
  if (code !== 0)
    throw new Error(
      `${command.join(" ")} exited ${code}\n${stdout}\n${stderr}\nIncomplete fixture retained at ${destination}`,
    );
  commands.push({ command, stdout });
  return stdout.trim();
}
async function fileHashes(
  root: string,
  prefix = "",
): Promise<Record<string, string>> {
  const hashes: Record<string, string> = {};
  for (const item of (
    await readdir(join(root, prefix), { withFileTypes: true })
  ).sort((a, b) => a.name.localeCompare(b.name))) {
    const path = join(prefix, item.name);
    if (item.isDirectory()) Object.assign(hashes, await fileHashes(root, path));
    else if (item.isFile())
      hashes[path] = createHash("sha256")
        .update(await readFile(join(root, path)))
        .digest("hex");
  }
  return hashes;
}
function sourceIdentity(cwd: string) {
  const git = (...args: string[]) => Bun.spawnSync(["git", ...args], { cwd });
  const head = git("rev-parse", "HEAD");
  const diff = git("diff", "HEAD", "--");
  const status = git("status", "--porcelain");
  return {
    checkout: cwd,
    revision: head.exitCode === 0 ? head.stdout.toString().trim() : null,
    workingDiffSha256:
      diff.exitCode === 0
        ? createHash("sha256").update(diff.stdout).digest("hex")
        : null,
    status: status.exitCode === 0 ? status.stdout.toString().trim() : null,
  };
}

await run(["git", "init", "-b", "main"]);
await run(["git", "config", "user.name", "Beacon rehearsal agent"]);
await run(["git", "config", "user.email", "rehearsal@example.invalid"]);
await run(["git", "config", "commit.gpgsign", "false"]);
await run([process.execPath, cliSource, "init", "--project", "BEC", "--json"]);
const generatedInstructions = await readFile(
  join(destination, "AGENTS.md"),
  "utf8",
).catch(() => "");
await cp(fixture, destination, { recursive: true });
const fixtureInstructions = await readFile(join(fixture, "AGENTS.md"), "utf8");
await writeFile(
  join(destination, "AGENTS.md"),
  `${generatedInstructions.trim()}\n\n${fixtureInstructions}`.trimStart(),
);
await mkdir(join(destination, "scripts"), { recursive: true });
const checker = join(sourceRoot, "scripts/extensions/check-beacon-browser.ts");
await cp(checker, join(destination, "scripts/check-beacon-browser.ts"));
await writeFile(
  join(destination, "scripts/docket.ts"),
  `// Current-source CLI wrapper generated by prepare-rehearsal.ts.\nconst child = Bun.spawn([process.execPath, ${JSON.stringify(cliSource)}, ...Bun.argv.slice(2)], { cwd: process.cwd(), stdin: "inherit", stdout: "inherit", stderr: "inherit" });\nprocess.exitCode = await child.exited;\n`,
);
await run([process.execPath, cliSource, "index"]);
// The lint JSON is a diagnostic array; its exit status determines failure.
await run([process.execPath, cliSource, "lint", "--json"]);
const source = {
  kind: "scripted-baseline-preparation",
  preparedAt: new Date().toISOString(),
  fixtureSource: sourceIdentity(sourceRoot),
  cliSource,
  cliIdentity: sourceIdentity(dirname(cliSource)),
  cliEntrySha256: createHash("sha256")
    .update(await readFile(cliSource))
    .digest("hex"),
  fixtureHashes: await fileHashes(fixture),
  browserChecker: {
    source: relative(sourceRoot, checker),
    sha256: createHash("sha256")
      .update(await readFile(checker))
      .digest("hex"),
  },
  preparationScriptSha256: createHash("sha256")
    .update(await readFile(import.meta.path))
    .digest("hex"),
  commands,
  evidenceBoundary:
    "Setup only. No feature implementation, review decision, observed agent response, external write or extension installation is represented by this file.",
};
await writeFile(
  join(destination, "rehearsal-source.json"),
  `${JSON.stringify(source, null, 2)}\n`,
);
await run(["git", "add", "."]);
await run([
  "git",
  "-c",
  "user.name=Beacon rehearsal setup",
  "-c",
  "user.email=rehearsal@example.invalid",
  "commit",
  "-m",
  "Prepare Beacon before bookmark export",
]);
const baselineRevision = await run(["git", "rev-parse", "HEAD"]);
console.log(
  JSON.stringify(
    {
      destination,
      baselineRevision,
      cliSource,
      workflow: join(destination, "docket/workflows/product-delivery.md"),
      commands: {
        app: "bun run start",
        baseline: "bun run test:baseline",
        export: "bun run test",
        browser: "bun run test:browser -- --output=/tmp/beacon-browser.json",
        docket: "bun run docket -- <arguments>",
      },
      expectedBaseline:
        "storage checks pass; export contract and browser export checks fail until a fresh agent implements the accepted feature",
    },
    null,
    2,
  ),
);
