// e2e for docket upgrade: a fixture repo vendored at shipped
// version 0.1.0 is upgraded to 0.2.0 (injected history), covering all four
// workflow outcomes — up-to-date, clean replace, clean merge, conflict — plus
// adapter regeneration, hand-authored skips, dry-run, and --file-task. The
// merge is the real `git merge-file`.

import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  ADAPTER_MARKER,
  DOCKET_WORKFLOWS,
  defaultConfigYaml,
  mergeCodexConfig,
  renderAgentSkillStub,
  renderDocketSection,
  type ShippedHistory,
} from "@docket/core";
import { AGENT_ADAPTERS, renderTargetSkillStub } from "./agent-adapters";
import { runUpgrade } from "./upgrade";

const OLD_BODY = `Intro line.

Step A.
Step B.
Step C.

Outro line.`;

const NEW_BODY = OLD_BODY.replace("Step B.", "Step B, revised.");

const HISTORY: ShippedHistory = [
  {
    version: "0.2.0",
    bodies: Object.fromEntries(DOCKET_WORKFLOWS.map((w) => [w.slug, NEW_BODY])),
  },
  {
    version: "0.1.0",
    bodies: Object.fromEntries(DOCKET_WORKFLOWS.map((w) => [w.slug, OLD_BODY])),
  },
];

const workflowFile = (slug: string, origin: string | undefined, body: string) =>
  `---\ntype: Workflow\ntitle: ${slug}\n${origin ? `origin: ${origin}\n` : ""}tags: [docket, workflow]\ntimestamp: 2026-01-01T00:00:00Z\n---\n\n${body}\n`;

let root: string;
const p = (...parts: string[]) => join(root, ...parts);

beforeAll(async () => {
  root = await mkdtemp(join(tmpdir(), "docket-upgrade-e2e-"));
  await writeFile(p("docket.yaml"), defaultConfigYaml("FIX", "docs/"));
  await mkdir(p("docs", "workflows"), { recursive: true });

  // The four workflow outcomes.
  await writeFile(
    p("docs/workflows/docket-task.md"),
    workflowFile("docket-task", "docket-task@0.2.0", NEW_BODY),
  );
  await writeFile(
    p("docs/workflows/docket-groom.md"),
    workflowFile("docket-groom", "docket-groom@0.1.0", OLD_BODY),
  );
  await writeFile(
    p("docs/workflows/docket-close.md"),
    workflowFile(
      "docket-close",
      "docket-close@0.1.0",
      `${OLD_BODY}\n\nLOCAL: also update the changelog.`,
    ),
  );
  await writeFile(
    p("docs/workflows/docket-standup.md"),
    workflowFile(
      "docket-standup",
      "docket-standup@0.1.0",
      OLD_BODY.replace("Step B.", "Step B, but my way."),
    ),
  );
  // Named after a shipped slug but customized before stamping — reported skip.
  await writeFile(
    p("docs/workflows/docket-freshness.md"),
    workflowFile("docket-freshness", undefined, "Entirely rewritten."),
  );
  // Genuinely user-authored — invisible to upgrade.
  await writeFile(
    p("docs/workflows/deploy.md"),
    "---\ntype: Workflow\ntitle: Deploy\n---\n\nShip it.\n",
  );

  // Adapters: a stale marked stub (old unversioned marker), a hand-authored one.
  const w = DOCKET_WORKFLOWS[0];
  if (!w) throw new Error("no workflows");
  await mkdir(p(".claude", "skills", w.slug), { recursive: true });
  await writeFile(
    p(".claude", "skills", w.slug, "SKILL.md"),
    renderAgentSkillStub(w, "docs/").replace(
      ADAPTER_MARKER,
      "<!-- generated by docket init — old text -->",
    ),
  );
  const hand = DOCKET_WORKFLOWS[1];
  if (!hand) throw new Error("need two workflows");
  await mkdir(p(".claude", "skills", hand.slug), { recursive: true });
  await writeFile(
    p(".claude", "skills", hand.slug, "SKILL.md"),
    "# my own skill, hands off\n",
  );

  await mkdir(p(".agents", "skills", w.slug), { recursive: true });
  await writeFile(
    p(".agents", "skills", w.slug, "SKILL.md"),
    renderAgentSkillStub(w, "docs/").replace(
      ADAPTER_MARKER,
      "<!-- generated by docket init — old Codex text -->",
    ),
  );
  await mkdir(p(".codex"), { recursive: true });
  await writeFile(
    p(".codex", "config.toml"),
    mergeCodexConfig('model = "gpt-5"\n').content.replace(
      /docket mcp@\d+\.\d+\.\d+/,
      "docket mcp@0.0.0",
    ),
  );

  // CLAUDE.md with a stale legacy span; no AGENTS.md.
  await writeFile(
    p("CLAUDE.md"),
    "# House rules\n\n<!-- >>> docket >>> -->\nstale section\n<!-- <<< docket <<< -->\n",
  );
});

afterAll(async () => {
  await rm(root, { recursive: true, force: true });
});

const byPath = (report: Awaited<ReturnType<typeof runUpgrade>>) =>
  new Map(report.items.map((i) => [i.path, i]));

describe("docket upgrade e2e", () => {
  test("dry run: full report, conflicts detected, nothing written", async () => {
    const report = await runUpgrade(
      root,
      { dryRun: true },
      { history: HISTORY, available: "0.2.0" },
    );
    const items = byPath(report);
    expect(items.get("docs/workflows/docket-task.md")?.action).toBe(
      "up-to-date",
    );
    expect(items.get("docs/workflows/docket-groom.md")?.action).toBe(
      "replaced",
    );
    expect(items.get("docs/workflows/docket-close.md")?.action).toBe("merged");
    expect(items.get("docs/workflows/docket-standup.md")?.action).toBe(
      "conflict",
    );
    expect(report.conflicts).toEqual(["docs/workflows/docket-standup.md"]);

    const untouched = await readFile(
      p("docs/workflows/docket-groom.md"),
      "utf8",
    );
    expect(untouched).toContain("origin: docket-groom@0.1.0");
    expect(untouched).toContain("Step B.");
  });

  test("real run: four outcomes on disk, adapters regenerated, hand-authored respected", async () => {
    const report = await runUpgrade(
      root,
      { fileTask: true },
      { history: HISTORY, available: "0.2.0" },
    );
    const items = byPath(report);

    // replaced: new body, origin bumped, timestamp untouched
    const groom = await readFile(p("docs/workflows/docket-groom.md"), "utf8");
    expect(groom).toContain("origin: docket-groom@0.2.0");
    expect(groom).toContain("Step B, revised.");
    expect(groom).toContain("timestamp: 2026-01-01T00:00:00Z");

    // merged: upstream revision AND local customization both present
    const close = await readFile(p("docs/workflows/docket-close.md"), "utf8");
    expect(items.get("docs/workflows/docket-close.md")?.action).toBe("merged");
    expect(close).toContain("Step B, revised.");
    expect(close).toContain("LOCAL: also update the changelog.");
    expect(close).toContain("origin: docket-close@0.2.0");

    // conflict: standard markers on disk
    const standup = await readFile(
      p("docs/workflows/docket-standup.md"),
      "utf8",
    );
    expect(standup).toContain("<<<<<<<");
    expect(standup).toContain("=======");
    expect(standup).toContain(">>>>>>>");

    // pre-stamp customized copy: reported, untouched
    expect(items.get("docs/workflows/docket-freshness.md")?.action).toBe(
      "skipped",
    );
    expect(
      await readFile(p("docs/workflows/docket-freshness.md"), "utf8"),
    ).toContain("Entirely rewritten.");

    // user-authored workflow: invisible
    expect(items.has("docs/workflows/deploy.md")).toBe(false);

    // adapters
    const w = DOCKET_WORKFLOWS[0];
    const hand = DOCKET_WORKFLOWS[1];
    if (!w || !hand) throw new Error("need two workflows");
    const stubPath = join(".claude", "skills", w.slug, "SKILL.md");
    expect(items.get(stubPath)?.action).toBe("regenerated");
    expect(await readFile(p(stubPath), "utf8")).toBe(
      renderAgentSkillStub(w, "docs/"),
    );
    const handPath = join(".claude", "skills", hand.slug, "SKILL.md");
    expect(items.get(handPath)?.action).toBe("skipped");
    expect(await readFile(p(handPath), "utf8")).toBe(
      "# my own skill, hands off\n",
    );
    const codexStubPath = join(".agents", "skills", w.slug, "SKILL.md");
    expect(items.get(codexStubPath)?.action).toBe("regenerated");
    expect(await readFile(p(codexStubPath), "utf8")).toBe(
      renderTargetSkillStub(AGENT_ADAPTERS.codex, w, "docs/"),
    );
    expect(items.get(".codex/config.toml")?.action).toBe("regenerated");
    expect(await readFile(p(".codex", "config.toml"), "utf8")).toBe(
      mergeCodexConfig('model = "gpt-5"\n').content,
    );

    // section span regenerated in place around surviving content
    const claudeMd = await readFile(p("CLAUDE.md"), "utf8");
    expect(items.get("CLAUDE.md")?.action).toBe("regenerated");
    expect(claudeMd.startsWith("# House rules\n\n")).toBe(true);
    expect(claudeMd).toContain("`docket overview --json`");
    expect(claudeMd).toContain("MCP-only client");
    expect(claudeMd).toContain("**Direct and tracked work**");
    expect(claudeMd).toContain("concrete direct request proceeds");
    expect(claudeMd).toContain("reference remains ambiguous");
    expect(claudeMd).toContain(
      "permitted only for explicit next-Docket-task or backlog selection",
    );
    expect(claudeMd.startsWith("# House rules\n")).toBe(true);
    expect(claudeMd).not.toContain("stale section");
    expect(claudeMd).toContain(renderDocketSection("FIX", "docs/").trimEnd());

    // --file-task: conflict filed into the fixture repo's own tracker
    expect(report.filedTask?.id).toBe("FIX-1");
    const task = await readFile(
      p("docs", report.filedTask?.path ?? ""),
      "utf8",
    );
    expect(task).toContain("docs/workflows/docket-standup.md");
    expect(task).toContain("status: todo");
  });

  test("second run is idempotent where it can be", async () => {
    const report = await runUpgrade(
      root,
      {},
      { history: HISTORY, available: "0.2.0" },
    );
    const items = byPath(report);
    expect(items.get("docs/workflows/docket-groom.md")?.action).toBe(
      "up-to-date",
    );
    expect(items.get("docs/workflows/docket-close.md")?.action).toBe(
      "up-to-date",
    );
    expect(items.get("CLAUDE.md")?.action).toBe("up-to-date");
    expect(items.get(".codex/config.toml")?.action).toBe("up-to-date");
    // The conflicted file already descends from 0.2.0 (origin was bumped), so
    // upgrade has nothing new to offer — the markers await manual resolution.
    expect(items.get("docs/workflows/docket-standup.md")?.action).toBe(
      "up-to-date",
    );
    expect(
      await readFile(p("docs/workflows/docket-standup.md"), "utf8"),
    ).toContain("<<<<<<<");
  });

  test("installs additive Codex lifecycle workflows and protects generated bindings", async () => {
    const fixture = await mkdtemp(join(tmpdir(), "docket-pickup-upgrade-"));
    const at = (...parts: string[]) => join(fixture, ...parts);
    try {
      await writeFile(at("docket.yaml"), defaultConfigYaml("FIX", "docs/"));
      await mkdir(at("docs", "workflows"), { recursive: true });
      const task = DOCKET_WORKFLOWS.find((w) => w.slug === "docket-task");
      if (!task) throw new Error("docket-task workflow missing");
      await mkdir(at(".agents", "skills", task.slug), { recursive: true });
      await writeFile(
        at(".agents", "skills", task.slug, "SKILL.md"),
        renderTargetSkillStub(AGENT_ADAPTERS.codex, task, "docs/"),
      );

      const installed = await runUpgrade(fixture, {});
      const pickupPath = at(".agents", "skills", "docket-pickup", "SKILL.md");
      const pickup = await readFile(pickupPath, "utf8");
      expect(pickup).toContain(ADAPTER_MARKER);
      expect(pickup).toContain("explicitly tracked Docket work only");
      expect(pickup).toContain("direct work bypasses Docket");
      expect(pickup).toContain("ambiguous references require resolution");
      expect(pickup).toContain("codex_app__set_thread_title");
      expect(pickup).toContain("Omit `threadId`");
      expect(
        installed.items.find(
          (item) => item.path === ".agents/skills/docket-pickup/SKILL.md",
        )?.reason,
      ).toBe("installed new pickup binding");
      expect(
        await readFile(at("docs", "workflows", "docket-pickup.md"), "utf8"),
      ).toContain("Only explicit next-Docket-task or backlog-selection");
      const epicPath = at(".agents", "skills", "docket-epic", "SKILL.md");
      const epic = await readFile(epicPath, "utf8");
      expect(epic).toContain(ADAPTER_MARKER);
      expect(epic).toContain("`Epic <ID> — <title>`");
      expect(epic).toContain("codex_app__set_thread_title");
      expect(epic).toContain("omit `threadId`");
      expect(epic).toContain("after every successful child pickup");
      expect(epic).toContain("before the completion or blocker receipt");
      expect(epic).toContain(
        "never apply the manager title to an isolated child",
      );
      expect(epic).toContain("one app task in an isolated Git worktree");
      expect(epic).toContain("canonical serial fallback");
      expect(
        installed.items.find(
          (item) => item.path === ".agents/skills/docket-epic/SKILL.md",
        )?.reason,
      ).toBe("installed new epic-supervision binding");
      expect(
        await readFile(at("docs", "workflows", "docket-epic.md"), "utf8"),
      ).toContain("origin: docket-epic@");

      await writeFile(pickupPath, `${pickup}\nstale generated text\n`);
      const regenerated = await runUpgrade(fixture, {});
      expect(
        regenerated.items.find(
          (item) => item.path === ".agents/skills/docket-pickup/SKILL.md",
        )?.action,
      ).toBe("regenerated");
      expect(await readFile(pickupPath, "utf8")).not.toContain(
        "stale generated text",
      );
      expect(await readFile(pickupPath, "utf8")).toContain(
        "direct work bypasses Docket",
      );

      await writeFile(pickupPath, "# My hand-authored pickup\n");
      const protectedRun = await runUpgrade(fixture, {});
      expect(
        protectedRun.items.find(
          (item) => item.path === ".agents/skills/docket-pickup/SKILL.md",
        )?.reason,
      ).toContain("hand-authored");
      expect(await readFile(pickupPath, "utf8")).toBe(
        "# My hand-authored pickup\n",
      );
    } finally {
      await rm(fixture, { recursive: true, force: true });
    }
  });
});
